# Generated by Django 5.2.15 on 2026-06-14 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshTokenFamily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_revoked", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_families",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefreshTokenLineage",
            fields=[
                (
                    "jti",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineage",
                        to="accounts.refreshtokenfamily",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="refreshtokenfamily",
            index=models.Index(
                fields=["user", "is_revoked"], name="accounts_re_user_id_b30d9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtokenfamily",
            index=models.Index(
                fields=["created_at"], name="accounts_re_created_32eab6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtokenlineage",
            index=models.Index(
                fields=["family", "is_active"], name="accounts_re_family__637268_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtokenlineage",
            index=models.Index(
                fields=["expires_at"], name="accounts_re_expires_a0bbc7_idx"
            ),
        ),
    ]
