# Generated by Django 5.2.15 on 2026-06-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0002_seed_pipeline"),
        ("leads", "0002_seed_lead_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="converted_deal_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_from_leads",
                to="deals.deal",
            ),
        ),
    ]
